name: labourlog
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  supabase_flutter: ^2.9.1
  flutter_svg: ^2.2.0
  url_launcher: ^6.3.1
  google_nav_bar: ^5.0.7
  flutter_staggered_grid_view: ^0.7.0
  csv: ^6.0.0
  share_plus: ^11.0.0
  lottie: ^3.3.1
  intl: ^0.20.2
  file_picker: ^10.2.0
  path_provider: ^2.1.5
  flutter_initicon: ^3.0.1
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.5.0
  image_cropper: ^9.1.0
  universal_html: ^2.2.4

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
  foreground_padding: 20%

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Ostent
      fonts:
        - asset: assets/fonts/Ostent-Regular.otf
        - asset: assets/fonts/Ostent-Heavy.otf
          weight: 700
        - asset: assets/fonts/Ostent-Light.otf
          weight: 300
